Repository wecode-bootcamp-korea/fullstack2-2nd-ADLIP-frontend, pull requests merged in 2021-11, with the labels that each got.

#20 [김지현] 소셜로그인/회원가입 기능 구현중
  package-lock.json
  public/images/kakaoLogo.png
  public/index.html
  src/components/KakaoLogin/AdlipLogin.js
  src/components/KakaoLogin/AdlipSignup.js
  src/components/KakaoLogin/KakaoLogin.js
  src/pages/LogIn/LogIn.js
  src/pages/SignUp/SignUp.js
Labels: Status: 수정중(임시)

#21 [성지수] 중간 카테고리 리스트 구현중
  package-lock.json
  package.json
  public/data/List/mainProduct.json
  public/data/Main/footerTotalData.json
  public/data/Main/mainCarousel.json
  public/data/Main/mainMiddleCarousel.json
  public/data/Main/mainMiddleCategory.json
  public/images/AdlipLogo.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.style.js
  src/components/Header/Header.js
  src/components/Header/Header.style.js
  src/components/MainCarousel/MainCarousel.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.style.js
  src/pages/Category/Category.js
  src/pages/Category/Category.style.js
  src/pages/FancyModalButton/FancyModalButton.js
  src/pages/List/CommonCardList.js
  src/pages/Main/Main.js
  src/pages/Main/Main.style.js
  src/pages/Main/MainCardList/MainCardList.js
  src/pages/Main/MainMiddleCategory.js
  src/styles/mixins.js
Labels: Status: Peer 리뷰 요청

#18 [김윤진] 상세페이지 레이아웃, 기본기능
  public/data/Detail/Detail.txt
  public/data/Detail/detailData.json
  src/pages/Detail/Detail.js
  src/pages/Detail/components/BookmarkIcon.js
  src/pages/Detail/components/ShareIcon.js
  src/pages/Detail/components/ToTopIcon.js
Labels: Status: Self Refactoring 완료, Status: Peer 리뷰 요청

#27 [김태규] 상세 페이지 캐러셀 구현중
  public/data/Detail/detailCarousel.json
  src/components/DetailCarousel/DetailCarousel.js
Labels: Status: Peer 리뷰 요청

#26 [김원영] 전체보기 페이지 / pagination 완료
  ;
  package-lock.json
  package.json
  public/data/List/card.json
  src/Routes.js
  src/pages/List/Card.js
  src/pages/List/List.js
  src/pages/List/ListAll.js
  src/pages/List/ListPage.js
Labels: Status: Peer 리뷰 요청

#22 [김태규] 리뷰페이지 구현중
  ;
  package-lock.json
  package.json
  public/data/Comment/comments.json
  src/API/api.js
  src/Routes.js
  src/components/DetailCarousel/DetailCarousel.js
  src/components/MainCarousel/MainCarousel.js
  src/pages/Comment/Comment.js
  src/pages/Comment/Components/AddReviewModal.js
  src/pages/Comment/Components/CommentHeader.js
  src/pages/Comment/Components/DeleteReview.js
  src/pages/Comment/Components/LikeThumbsUp.js
  src/pages/Comment/Components/ModalImageSlider.js
  src/pages/Comment/Components/Pagination.js
  src/pages/Comment/Components/ReviewCard.js
  src/pages/Comment/Components/ReviewHandler.js
  src/pages/Comment/Components/ReviewImages.js
  src/pages/Comment/Components/UserInfo.js
  src/pages/Detail/Detail.js
  src/styles/theme.js
Labels: Status: 수정중(임시)

#28 [김지현] 소셜 로그인 및 일반 로그인/회원가입 리팩토링중
  .env
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/components/KakaoLogin/AdlipLogin.js
  src/components/KakaoLogin/AdlipSignup.js
  src/components/KakaoLogin/KakaoLogin.js
  src/pages/LogIn/LogIn.js
  src/pages/SignUp/SignUp.js
Labels: Status: Peer 리뷰 요청, Status: 수정중(임시)

#34 Add: 회원가입, 로그인 기능, 로그인 상태유지 구현
  src/Routes.js
  src/components/Header/Header.js
  src/components/KakaoLogin/AdlipLogin.js
  src/components/KakaoLogin/AdlipSignup.js
  src/components/KakaoLogin/KakaoLogin.js
  src/pages/SignUp/SignUp.js
Labels: Status: Peer 리뷰 요청

#37 Add: 리뷰 페이지 및 캐러셀 백엔드에 맞게 코드 수정
  public/data/Comment/tempComments.json
  src/API/api.js
  src/Routes.js
  src/components/DetailCarousel/DetailCarousel.js
  src/components/Header/Header.js
  src/components/KakaoLogin/KakaoLogin.js
  src/pages/Comment/Comment.js
  src/pages/Comment/Components/AddReviewModal.js
  src/pages/Comment/Components/CommentHeader.js
  src/pages/Comment/Components/LikeThumbsUp.js
  src/pages/Comment/Components/ModalImageSlider.js
  src/pages/Comment/Components/Paging.js
  src/pages/Comment/Components/ReviewCard.js
  src/pages/Comment/Components/ReviewHandler.js
  src/pages/Comment/Components/ReviewImages.js
  src/pages/Detail/Detail.js
  src/styles/theme.js
Labels: Status: Peer 리뷰 요청

#46 [김지현] 로그인, 로그아웃 리팩토링
  src/PublicRoute.js
  src/Routes.js
  src/components/Header/Header.js
  src/components/Header/HeaderLogin.js
  src/components/Header/HeaderLogout.js
  src/components/KakaoLogin/AdlipLogin.js
  src/components/KakaoLogin/AdlipSignup.js
  src/components/KakaoLogin/KakaoLogin.js
  src/pages/Main/Main.js
Labels: Status: Peer 리뷰 요청

#45 [김태규] 리팩토링 중
  public/data/Comment/tempComments.json
  src/components/DetailCarousel/DetailCarousel.js
  src/pages/Comment/Comment.js
  src/pages/Comment/Components/AddReviewModal.js
  src/pages/Comment/Components/CommentHeader.js
  src/pages/Comment/Components/DeleteReview.js
  src/pages/Comment/Components/LikeThumbsUp.js
  src/pages/Comment/Components/ModalImageSlider.js
  src/pages/Comment/Components/Paging.js
  src/pages/Comment/Components/Rating.js
  src/pages/Comment/Components/ReviewCard.js
  src/pages/Comment/Components/ReviewHandler.js
  src/pages/Comment/Components/ReviewImages.js
  src/pages/Comment/Components/UserInfo.js
Labels: Status: Peer 리뷰 요청

#53 Refactor: 피드페이지 리팩토링
  src/pages/Detail/Detail.js
  src/pages/Feed/components/FeedCard.js
  src/pages/Feed/components/FeedCardHeader.js
  src/pages/Feed/components/FeedCardImg.js
  src/pages/Feed/components/FeedCardLessText.js
  src/pages/Feed/components/FeedCardLike.js
  src/pages/Feed/components/FeedCardMoreText.js
  src/pages/Feed/components/FeedCardName.js
  src/pages/Feed/components/FeedCardText.js
Labels: Status: Peer 리뷰 요청
